package fr.jaetan.jmedia.ui.theme.themes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val  SunsetSiennaLightColorScheme = lightColorScheme(
    primary = Color(0xFF965A29),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD8C2),
    onPrimaryContainer = Color(0xFF321100),
    inversePrimary = Color(0xFFD17B49),
    secondary = Color(0xFF775650),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBB7),
    onSecondaryContainer = Color(0xFF2C160E),
    tertiary = Color(0xFF745B5B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDAD4),
    onTertiaryContainer = Color(0xFF2D1514),
    background = Color(0xFFFFFBFA),
    onBackground = Color(0xFF201A18),
    surface = Color(0xFFFFFBFA),
    onSurface = Color(0xFF201A18),
    surfaceVariant = Color(0xFFF4DED9),
    onSurfaceVariant = Color(0xFF534341),
    surfaceTint = Color(0xFF965A29),
    inverseSurface = Color(0xFF31302C),
    inverseOnSurface = Color(0xFFF9EDE9),
    error = Color(0xFFBA1B1B),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410E0D),
    outline = Color(0xFF84746E),
    outlineVariant = Color(0xFFF4DED9),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFBFA),
    surfaceDim = Color(0xFFF5ECE7),
    surfaceContainer = Color(0xFFFFFBFA),
    surfaceContainerHigh = Color(0xFFF6E2DA),
    surfaceContainerHighest = Color(0xFFF9E8E0),
    surfaceContainerLow = Color(0xFFE7DAD1),
    surfaceContainerLowest = Color(0xFFE0D0C8),
)

val SunsetSiennaDarkColorScheme = darkColorScheme(
    primary = Color(0xFFD17B49),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF5D2A00),
    onPrimaryContainer = Color(0xFFFFD8C2),
    inversePrimary = Color(0xFF613D2B),
    secondary = Color(0xFFA56E43),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF432C0B),
    onSecondaryContainer = Color(0xFFFFDBB7),
    tertiary = Color(0xFFB25D5C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF732522),
    onTertiaryContainer = Color(0xFFFFDAD4),
    background = Color(0xFF201A18),
    onBackground = Color(0xFFEDE0DC),
    surface = Color(0xFF201A18),
    onSurface = Color(0xFFEDE0DC),
    surfaceVariant = Color(0xFF534341),
    onSurfaceVariant = Color(0xFFD8C2BE),
    surfaceTint = Color(0xFFD17B49),
    inverseSurface = Color(0xFFEDE0DC),
    inverseOnSurface = Color(0xFF201A18),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFF410001),
    onErrorContainer = Color(0xFFFFDAD4),
    outline = Color(0xFF958F8C),
    outlineVariant = Color(0xFFD8C2BE),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF382F2C),
    surfaceDim = Color(0xFF2C2523),
    surfaceContainer = Color(0xFF382F2C),
    surfaceContainerHigh = Color(0xFF4E4542),
    surfaceContainerHighest = Color(0xFF625953),
    surfaceContainerLow = Color(0xFF2C2523),
    surfaceContainerLowest = Color(0xFF1F1917),
)