on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      #Lint
      - name: Lint
        uses: alaegin/Detekt-Action@v1.23.5
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt.yml
          fail_on_error: false