on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      #Linter
      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.20

      - name: Run detekt
        run: detekt-cli --version