on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master

      #Lint
      - name: Code style review
        uses: DominuS-RU/Detekt-Action@master
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_level: warning
          reviewdog_filter: nofilter