on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master

      - name: Create local.properties
        run: |
          touch local.properties
          echo 'github.token="${{ secrets.GIT_TOKEN }}"' >> local.properties
          echo 'theMovieDb.token="${{ secrets.THE_MOVIE_DB_TOKEN }}"' >> local.properties

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      #Linter
      - name: Linter
        run: ./gradlew detekt