on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master

      #Lint
      - name: Code style review
        uses: alaegin/Detekt-Action@v1.23.5
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_level: info