on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      #Lint
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review