on: push
name: Create Release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: build release
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk

      - name: Get Previous tag
        id: previousTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.1

      - name: Parse changelog.md
        run: |
          r=$(cat ${{ github.workspace }}/changelog.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT  

      - name: Create Draft Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk
          asset_name: ${{ steps.previousTag.outputs.tag }}.apk
          tag: ${{ steps.previousTag.outputs.tag }}
          overwrite: true
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}