on: push
name: Create Release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Take global info
      - name: Get app version
        run: bash ./app_version.sh

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.APP_VERSION }}
          force_push_tag: true

      - name: Get Previous tag
        id: previousTag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Parse changelog.md
        id: readRelease
        run: bash ./parse_changelog.sh

      # Generate temp files
      - name: Create local.properties
        run: touch local.properties

      - name: Generate local.properties content
        run: |
          echo 'github.token="${{ secrets.GIT_TOKEN }}"' >> local.properties
          echo 'theMovieDb.token="${{ secrets.THE_MOVIE_DB_TOKEN }}"' >> local.properties
          echo 'keystore.password="${{ secrets.KEYSTORE_PASSWORD }}"' >> local.properties
          echo 'keystore.alias="${{ secrets.KEYSTORE_ALIAS }}"' >> local.properties
          echo 'keystore.key.password="${{ secrets.KEYSTORE_KEY_PASSWORD }}"' >> local.properties

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: keystore.jks
          fileDir: ${{ github.workspace }}/app/
          encodedString: ${{ secrets.KEYSTORE }}

      # Build
      - name: Build release
        run: ./gradlew assembleDemo

      # Manage release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/app/build/outputs/apk/demo/app-demo.apk

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.previousTag.outputs.tag }}
          body: ${{ env.RELEASE_BODY }}
          file: ${{ github.workspace }}/app/build/outputs/apk/demo/app-demo.apk